WebSystems/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app.urls")),
    path("user/", include("userauths.urls")),
    path("chat/", include("chat.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
# urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path('', views.index, name='index'),
    path('projects/', views.projects, name='projects'),

    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),

    path('splash/', views.splash, name='splash'),

    # Add similar URLs for signup, logout, etc.
]

userauths/urls.py
# urls.py
from django.urls import path
from . import views

app_name = "userauths"

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout, name='logout'),

    path('register/', views.register, name='register'),

    # Add similar URLs for signup, logout, etc.
]

templates/app/index.html
{%extends "partials/base.html"%}
{%load static%}
{%block title%}Home{%endblock%}

{%block content%}
<style>
    .bbg {
          background: #E1F7F5;
    }
    #hover {
        background: black;
    }
    .hoverme {
        background: #6367AF;
        color: #fff;
    }
    .hoverme:hover {
        background: #313559;
        color: #fff;
    }
    .hoverme_outline {
        border: 2px solid #6367AF;
        color: #6367AF;
    }
    .hoverme_outline:hover {
        border: 2px solid #313559;
        color: #313559;
    }


</style>

<div class="px-4 background py-3 my-5 text-center">
    <div class="badge mb-3 shadow-sm bg-warning rounded-pill">Whats new in AWS ?</div>

    <img class="d-block mx-auto mb-4" src="{%static 'app_images/AWS LOGO.png'%}" alt="" width="100">
    <!--    <h1 class="display-5 fw-bold text-body-emphasis">Innovate. Transform. Conquer.</h1>-->
    <h1 class="display-5 fw-bold text-body-emphasis">Analytics web systems</h1>

    <div class="col-lg-8 classiq mx-auto">
        <p class="lead mb-4 fw-normal" style="font-size: 17px;">Innovate your strategies, Transform your data, Conquer
            your goals—take
            the first
            and remarkable step with
            Analytics Web Systems today.</p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a href="#" style="" class="btn hoverme btn-lg px-4 gap-3">Get started</a>
            <a href="#" style="" class="btn hoverme_outline btn-lg px-4 gap-3">Explore</a>
        </div>
    </div>
</div>
<!--PROJECTS-->

<div class="d-flex justify-content-between align-items-center mb-2">
    <h2>Our portfolio</h2>
    <a href="{%url 'app:projects'%}" class="text-decoration-none">See all <span
            class="badge bg-body-tertiary text-success rounded-pill">{{project_count}}+</span></a>

</div>

<div class="container bbg p-3 rounded-3">
    <div class="row d-flex justify-content-between">
        {%for pro in projects%}
        <div class="col-md-6 my-2 col-lg-6 sm-4">
            <a href="{%url 'app:project_detail' pro.id%}" class="text-decoration-none text-dark">
                <div class="card shadow-sm">
                    <img src="{{pro.image.url}}" class="" width="100%" height="225" alt="" style="object-fit: cover;">
                    <div class="card-body">
                        <div class="d-flex align-items-center justify-content-between">
                            <h5 class="card-title mx-2"><strong>{{pro.title}}</strong></h5>

                            <span class="badge text-bg-dark">{{pro.client}}</span>

                        </div>
                        {% with words=pro.description|wordcount %}
                        {% if words > 9 %}
                        <p class="card-text">
                            {{ pro.description|slice:":100" }} ... <a href="{%url 'app:project_detail' pro.id%}">Read
                            more</a>
                        </p>
                        {% else %}
                        <p class="card-text">
                            {{ pro.description }}
                        </p>
                        {% endif %}
                        {% endwith %}
                        <div class="d-flex justify-content-between">
                            <a href="#"
                               class="d-flex mb-2 align-items-center link-body-emphasis text-decoration-none">
                                <img src="{% static 'app_images/default.png'%}" alt="" width="30" height="30" class="rounded-circle me-2">
                                <strong>{%if pro.champion%}{{pro.champion.user.username}}{%else%}Someone{%endif%} <i class="bi text-primary bi-patch-check-fill"></i></strong>
                            </a>
                            <div class="d-flex align-items-center">
                                {%for t in pro.technologies_used.all%}
                                <span class="badge mb-2 mx-1 shadow-sm rounded-pill bg-body-tertiary text-info">{{t.name}}</span>
                                {%endfor%}
                            </div>

                        </div>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group w-100">
                                <a href="{%url 'app:project_detail' pro.id%}" id="hover"
                                   class="btn border btn-sm bg-body-tertiary">View</a>

                            </div>
                        </div>
                    </div>
                </div>

            </a>
        </div>
        {%endfor%}

    </div>
</div><br><br>

<!--TESTIMONIALS-->
<h3>Testimonials</h3>
<p style="" class="fs-6">See what our past clients have to say about us</p>
<div class="container d-flex justify-content-between p-2 rounded-3">
    <div class="row">
        {% for test in testimonials%}
        <div class="col-lg-6 col-md-6 my-2 text-center">
            <div class="card p-2 text-bg-info shadow-sm text-white">
                <div class="text-center">
                    <img style="object-fit: cover;" width="80" class="rounded-circle"
                         src="https://i.pinimg.com/564x/d4/2d/9c/d42d9c6ff7455237b43289c8f3ab6b25.jpg" alt="">
                    <h4 class="fw-normal"><strong>{{test.user.username}}</strong></h4>
                    <p style="font-size: 14px;">{{test.content}}</p>
                    <div class="text-center">
                        <a href="#" class="btn btn-sm w-50 bg-body-secondary text-info">view details</a>

                    </div>
                </div>
            </div>

        </div>
        {%endfor%}
    </div>
</div>
{%endblock%}

templates/app/project_detail.html
{%extends "partials/base.html"%}
{%block title%}Project detail{%endblock%}
{%load static%}
{%block content%}

<style>
    body {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
    .container {
        padding: 20px 10px;
    }
    .project-image {
        width: 100%;
        max-height: 500px;
        overflow: hidden;
        margin-bottom: 20px;
    }
    .project-image img {
        width: 100%;
        height: auto;
    }
    .project-details {
        background-color: #f9f9f9;
        padding: 20px;
        border-radius: 10px;
    }
    .project-details h2 {
        font-size: 24px;
        margin-bottom: 10px;
    }
    .project-details p {
        font-size: 16px;
        line-height: 1.6;
        margin-bottom: 10px;
    }
    .bg-body-tertiary {
        background-color: rgba(0, 0, 0, 1.4);
    }
    .comment-box {
        border: 1px solid #ccc;
        border-radius: 10px;
        margin-bottom: 10px;
        padding: 7px;
}

#comment-textarea {
  width: 100%;
  border: none;
  outline: none;
  resize: vertical; /* Allow vertical resizing */
}
</style>
<div class="container-fluid project-image">
    <!--    <div class="">-->
    <img src="{{ project.image.url }}" alt="{{ project.title }}">
    <!--    </div>-->
</div>
<!--<div class="container">-->
<div class="project-details">
    <div class="d-flex align-items-center justify-content-between">
        <h2><strong>{{ project.title }}</strong></h2>
        <h6><strong>Client:</strong> <span class="badge bg-dark shadow-sm">{{ project.client }}</span></h6>
    </div>
    <small class="text-muted"><i class="bi bi-calendar3"></i> {{ project.start_date }} - {{ project.end_date }}</small>

    <p><strong>Description:</strong> {{ project.description }}</p>
    <hr>
    <a href="#"
       class="d-flex mb-2 align-items-center link-body-emphasis text-decoration-none">
        <img src="https://github.com/mdo.png" alt="" width="40" height="40"
             class="rounded-circle me-2">
        <strong>{%if project.champion%}{{project.champion.user.username}}{%else%}Someone{%endif%} <i
                class="bi text-primary bi-patch-check-fill"></i></strong>
    </a>
    <p><strong>Service: </strong><span class="badge bg-body-secondary text-primary">{{project.service.title}}</span></p>
    <p><strong>Technologies used: </strong>{%for t in project.technologies_used.all%}<span
            class="badge bg-body-secondary text-secondary">{{t.name}}</span> {%endfor%}</p>

    <hr>
</div>
<hr>
<div class="container">
    <div class="d-flex justify-content-between align-items-center">
        <h4>Comments {%if comment_count != 0%}<span class="badge bg-body-tertiary text-primary">{{comment_count}}</span>{%endif%}
        </h4>
        <p>Sort <i class="bi bi-filter-circle-fill"></i>
        </p>
    </div>
    {%if comments%}
    <div class="row g-4 py-2 row-cols-md-3 flex-wrap">
        {% for comment in comments %}
        <div class="col col-md-4 col-sm-4 col-lg-4 border mx-2 rounded-2 p-2 shadow-sm">
            <div class="d-flex">
                <h6 class="fs-5 text-body-emphasis text-primary">{{comment.user.username}}</h6>
                <!--                <small class="text-muted">{{comment.created_at|timesince}}</small>-->

            </div>
            <p class="fs-6">{{comment.content}}.</p>
            <div class="d-flex justify-content-center align-items-center px-2">
                <a href="#" class="icon-link"><i class="bi bi-pencil-square mx-2"></i></a>
                <a href="#" class="icon-link"><i class="bi bi-trash-fill mx-2"></i></a>
                <a href="#" class="icon-link"><i class="bi bi-heart mx-2"></i></a>
            </div>
        </div>
        {% endfor %}
    </div>

    {%else%}
    <div class="text-center">
        <img width="120" src="{%static 'app_images/comment.png'%}" alt="">
    </div>
    <h6 class="text-center mt-2">
        No comments yet <br>
        <a href="#">Be the first to comment</a>
    </h6>
    {%endif%}
    <div class="container">
        <form method="post" action="{% url 'app:project_detail' project_id=project.id %}">
            {% csrf_token %}
            <div class="comment-box">
                {{ form.content.errors }}
                <textarea id="comment-textarea" name="content" rows="2" placeholder="Write comments here"
                          required></textarea>
            </div>
            <div class="text-center mt-4">
                <button class="btn btn-dark rounded-pill w-50" type="submit"><i class="bi bi-send-fill"></i> Comment
                </button>

            </div>
        </form>

        <!--        <form method="post" action="{% url 'app:project_detail' project_id=project.id %}">-->
        <!--            {% csrf_token %}-->
        <!--            {{ form.as_p }}-->
        <!--            <button type="submit">Submit</button>-->
        <!--        </form>-->
    </div>
</div>
<hr>
<!--<br><br><br><br><br><br><br><br><br><br>-->

{%endblock%}

templates/app/projects.html
{%extends "partials/base.html"%}
{%load static%}
{%block title%}Projects{%endblock%}

{%block content%}
<div class="d-flex align-items-center">
    <h4 class="m-2">Projects</h4>
    <span class="badge mt-1 bg-body-tertiary text-secondary">{{pro_count}}</span>
</div>

<div class="container bbg p-3 rounded-3">
    <div class="row d-flex justify-content-between">
        {%for pro in projects%}
        <div class="col-md-6 my-2 col-lg-6 sm-4">
            <a href="{%url 'app:project_detail' pro.id%}" class="text-decoration-none text-dark">
                <div class="card shadow-sm">
                    <img src="{{pro.image.url}}" class="" width="100%" height="225" alt="" style="object-fit: cover;">
                    <div class="card-body">
                        <div class="d-flex align-items-center justify-content-between">
                            <h5 class="card-title mx-2"><strong>{{pro.title}}</strong></h5>

                            <span class="badge text-bg-dark">{{pro.client}}</span>

                        </div>
                        {% with words=pro.description|wordcount %}
                        {% if words > 9 %}
                        <p class="card-text">
                            {{ pro.description|slice:":100" }} ... <a href="{%url 'app:project_detail' pro.id%}">Read
                            more</a>
                        </p>
                        {% else %}
                        <p class="card-text">
                            {{ pro.description }}
                        </p>
                        {% endif %}
                        {% endwith %}
                        {%for t in pro.technologies_used.all%}
                        <span class="badge mb-2 shadow-sm rounded-pill bg-body-tertiary text-info">{{t.name}}</span>
                        {%endfor%}
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group w-100">
                                <a href="{%url 'app:project_detail' pro.id%}" id="hover"
                                   class="btn border btn-sm bg-body-tertiary">View</a>

                            </div>
                        </div>
                    </div>
                </div>

            </a>
        </div>
        {%endfor%}

    </div>
</div><br><br>
{%endblock content%}

templates/app/splash.html
{%extends "partials/base2.html"%}
{%load static%}
{%block title%}Splash{%endblock%}

{%block content%}
<style>
    body {
        background: #32012F;
    }
    .more {
        padding-top: 5rem;
    }
    h4 {
        font-size: 33px;
        color: white;
        margin-bottom: 13px;
    }
    p {
        font-size: 18px;
        color: white;
        opacity: 90%;
    }
    @media screen and (min-width: 500px) {
            .more {
                padding-top: 2rem;
            }
    }
</style>
<!--<h1>Splash</h1>-->

<div class="text-center more">
    <img class="mb-3" width="250" src="{%static 'app_images/Asset1 - Copy.png'%}" alt="">
    <div class="mt-3">
        <h4 style="font-family: 'Cutive', system-ui;">Analytic & <br> web systems ltd</h4><br>
        <p style="font-family: 'Pacifico', system-ui;">Your all in one tech solutions..</p>
    </div>
    <div class="d-flex mt-5 flex-column align-items-center">
        <a href="{%url 'userauths:login'%}" class="btn w-100 btn-lg my-2 rounded-pill btn-outline-light">Login</a>
        <a href="{%url 'userauths:register'%}" class="btn w-100 btn-lg my-2 rounded-pill btn-light">Get started</a>

    </div>
    <div class="text-center mt-3">
        <p style="font-size: 16px; color: white;" class="display-6">Version 1.0.0</p>
    </div>

</div>
{%endblock%}