WebSystems/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app.urls")),
    path("user/", include("userauths.urls")),
    path("chat/", include("chat.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
# urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path('', views.index, name='index'),
    path('projects/', views.projects, name='projects'),

    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),

    path('splash/', views.splash, name='splash'),

    # Add similar URLs for signup, logout, etc.
]

chat/urls.py
# urls.py

from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path('choose-representative/', views.choose_representative, name='choose_representative'),
    path('send-message/<int:representative_id>/', views.send_message, name='send_message'),
    path('conversation-detail/<int:representative_id>/', views.conversation_detail, name='conversation_detail'),
    path('inbox/', views.inbox, name='inbox'),
]

userauths/urls.py
# urls.py
from django.urls import path
from . import views

app_name = "userauths"

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout, name='logout'),

    path('register/', views.register, name='register'),

    # Add similar URLs for signup, logout, etc.
]

templates/partials/base.html
<!doctype html>
{%load static%}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{%block title%}{%endblock%} | Web systems &copy;</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cutive&family=Pacifico&family=Special+Elite&display=swap"
          rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css2?family=Sedan:ital@0;1&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="icon" type="icon/png" href="{% static 'app_images/AWS LOGO.png' %}" style="width: 35px; height: 35px;">

</head>
<style>
    <!--    .active {-->
    <!--        border-bottom: 2px solid white;-->
    <!--    }-->
        body {
                margin: 0;
                padding: 0;
                box-sizing: border-box;
                font-family: "Sedan", serif;
            }
        .navbar {
            background: #1E0342;
            min-height: 80px;
        }
        .footer-container {
            background: #1E0342;

        }
        #loading-screen {
      position: fixed;
      z-index: 9999;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background-color: rgba(255, 255, 255, 0.9);
      display: flex;
      justify-content: center;
      align-items: center;
    }

    .spinner {
      border: 4px solid #f3f3f3;
      border-top: 4px solid #3498db;
      border-radius: 50%;
      width: 50px;
      height: 50px;
      animation: spin 1s linear infinite;
    }

    @keyframes spin {
      0% {
        transform: rotate(0deg);
      }
      100% {
        transform: rotate(360deg);
      }
    }
    /* Style for floating message icon */
        .message-icon {
            position: fixed;
            bottom: 100px;
            right: 40px;
            z-index: 10000; /* Ensure it's above other content */
            shadow: 2px black rgba(0,0,0,0.6);
            /* Add any additional styling you need */
        }

        /* Style for tooltip */
        .tooltip {
            position: absolute;
            background-color: rgba(0, 0, 0, 0.7);
            color: #fff;
            padding: 5px;
            border-radius: 5px;
            display: none;
        }

        .message-icon:hover + .tooltip {
            display: block;
        }
    .hoverme {
        background: #6367AF;
        color: #fff;
    }
    .hoverme:hover {
        background: #313559;
        color: #fff;
    }
    .hoverme_outline {
        border: 2px solid #6367AF;
        color: #6367AF;
    }
    .hoverme_outline:hover {
        border: 2px solid #313559;
        color: #313559;
    }
</style>


<body>
<!--NAVBAR-->
<nav class="navbar navbar-expand-md navbar-dark sticky-top shadow-sm" aria-label="Fourth navbar example">
    <div class="container-fluid container py-2">
        <a class="navbar-brand" style="" href="/"><strong>AWS.</strong></a>
        <div class="d-flex">
            <!--            <a href="#" class="bi bi-app-indicator text-white fs-3"></a>-->

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04"
                    aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="navbarsExample04">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{%url 'app:projects'%}">Projects</a>
                </li>
                <li class="nav-item d-flex align-items-center">
                    <a class="nav-link active" aria-current="page" href="{%url 'chat:inbox'%}">Inbox</a>
                    <span class="badge bg-success pb-2">3</span>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown"
                       aria-expanded="false">More</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item d-flex align-items-center px-3" href="#">
                            <i class="bi fs-5 text-dark bi-person-bounding-box mx-2"></i>
                            My profile</a></li>
                        <li><a class="dropdown-item d-flex align-items-center px-3" href="#">
                            <i class="bi fs-5 text-dark bi-gear-fill mx-2"></i>
                            Settings</a></li>
                        <hr class="dropdown-divider">
                        <li><a class="dropdown-item d-flex align-items-center px-3" href="#">
                            <i class="bi fs-5 text-dark bi-person-bounding-box mx-2"></i>
                            Something else here</a></li>
                    </ul>
                </li>
            </ul>
            <form role="search">
                <input class="form-control rounded-5" type="search" placeholder="Search" aria-label="Search">
            </form>
            <div class="div m-2">
                {%if user.is_authenticated%}
                <a href="{%url 'userauths:logout'%}" class="btn hoverme_outline"><i
                        class="bi fs-6 bi-box-arrow-left"></i> Sign off</a>
                {%else%}
                <a href="{%url 'app:splash'%}" class="btn hoverme">Login / Register</a>
                {%endif%}


            </div>
            <!--            <div class="mx-3">-->

            <!--            </div>-->
        </div>
    </div>
</nav>
<!--ALERT-->
{% if messages %}
{% for message in messages %}
<div id="alertDiv" class="container">
    <div class="alert text-center alert-{{ message.tags }}">
        <strong><span><i class="bi bi-bell-fill"></i></span> {{ message }}</strong>
    </div>
</div>

{% endfor %}
<script>
    // Function to remove the alert div after 8 seconds
    setTimeout(function(){
        var alertDiv = document.getElementById('alertDiv');
        if (alertDiv) {
            alertDiv.remove();
        }
    }, 5000); // 8000 milliseconds = 8 seconds
</script>
{% endif %}
<!--NAVBAR END-->
<div id="loading-screen">
    <div class="spinner"></div>
</div>
<script>
    window.addEventListener('load', function () {
      document.getElementById('loading-screen').style.display = 'none';
    });
</script>

<a href="{% url 'chat:inbox' %}" class="message-icon px-2 shadow-md rounded-circle bg-dark">
    <div class="d-flex flex-column align-items-center">
        <span class="badge bg-primary position-relative">Chat us</span>
        <i class="bi shadow-md text-white fs-2 bi-chat-quote-fill"></i><span
            class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle">
    <span class="visually-hidden">New alerts</span>
  </span>

    </div>

</a>
<div class="container">
    {%block content%}{%endblock%}
</div>

<!--FOOTER-->
<div class="container-fluid footer-container text-white">
    <footer class="d-flex flex-wrap sticky-bottom justify-content-between align-items-center py-3 mt-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-body-dark text-white text-decoration-none lh-1">
                <strong class="fs-2">AWS.</strong>
            </a>
            <span class="mb-3 mb-md-0 text-white">©web systems, Inc</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-white" href="#">
                <i class="bi bi-github"></i>
            </a></li>
            <li class="ms-3"><a class="text-white" href="#">
                <i class="bi bi-twitter-x"></i>
            </a></li>
            <li class="ms-3"><a class="text-white" href="#">
                <i class="bi bi-linkedin"></i>
            </a></li>
        </ul>
    </footer>
</div>
<!--FOOTER END-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

templates/partials/base2.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{%block title%}{%endblock%} | Web systems &copy;</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cutive&family=Pacifico&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<style>
    * {
        box-sizing: border-box;
    }
    #loading-screen {
  position: fixed;
  z-index: 9999;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(255, 255, 255, 0.9);
  display: flex;
  justify-content: center;
  align-items: center;
}

.spinner {
  border: 4px solid #f3f3f3;
  border-top: 4px solid #3498db;
  border-radius: 50%;
  width: 50px;
  height: 50px;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}

</style>
<body>
<!--ALERT-->
{% if messages %}
{% for message in messages %}
<div id="alertDiv" class="container">
    <div class="alert text-center alert-{{ message.tags }}">
        <strong><span><i class="bi bi-bell-fill"></i></span> {{ message }}</strong>
    </div>
</div>

{% endfor %}
<script>
    // Function to remove the alert div after 8 seconds
    setTimeout(function(){
        var alertDiv = document.getElementById('alertDiv');
        if (alertDiv) {
            alertDiv.remove();
        }
    }, 5000); // 8000 milliseconds = 8 seconds
</script>
{% endif %}

<div id="loading-screen">
    <div class="spinner"></div>
</div>
<script>
    window.addEventListener('load', function () {
      document.getElementById('loading-screen').style.display = 'none';
    });
</script>
<div class="container">
    {%block content%}{%endblock%}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>