WebSystems/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app.urls")),
    path("user/", include("userauths.urls")),
    path("chat/", include("chat.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
# urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path('', views.index, name='index'),
    path('projects/', views.projects, name='projects'),

    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),

    path('splash/', views.splash, name='splash'),

    # Add similar URLs for signup, logout, etc.
]

chat/urls.py
# urls.py

from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path('choose-representative/', views.choose_representative, name='choose_representative'),
    path('send-message/<int:representative_id>/', views.send_message, name='send_message'),
    path('conversation-detail/<int:representative_id>/', views.conversation_detail, name='conversation_detail'),
    path('inbox/', views.inbox, name='inbox'),
]

chat/models.py
from django.db import models
from userauths.models import User


# Create your models here.
class Representative(models.Model):
    profile_pic = models.ImageField(upload_to='rep_profile', null=True, blank=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Conversation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    representative = models.ForeignKey(Representative, on_delete=models.CASCADE)
    # Add any additional fields you need for your conversation


class Message(models.Model):
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE, related_name='messages')
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

# class Message(models.Model):
#     sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
#     recipient = models.ForeignKey(Representative, on_delete=models.CASCADE, related_name='received_messages')
#     content = models.TextField()
#     timestamp = models.DateTimeField(auto_now_add=True)

chat/forms.py
from django import forms
from .models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content']
        widget = {
            "content": forms.Textarea(attrs={
                "class": "form-control",
                "id": "messageForm",
            })
        }

chat/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Representative, Message, Conversation
from django.contrib import messages
from .forms import MessageForm


# Create your views here.
@login_required
def choose_representative(request):
    representatives = Representative.objects.all()
    return render(request, 'chat/choose_representative.html', {'representatives': representatives})


@login_required
def send_message(request, representative_id):
    representative = Representative.objects.get(id=representative_id)
    conversation = Conversation.objects.filter(user=request.user, representative=representative).first()
    if not conversation:
        conversation = Conversation.objects.create(user=request.user, representative=representative)

    all_messages = Message.objects.filter(conversation=conversation).order_by('timestamp')

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            Message.objects.create(conversation=conversation, sender=request.user, content=content)
            messages.success(request, "Your message has been delivered")
            return redirect('chat:conversation_detail', representative_id=representative_id)
    else:
        form = MessageForm()

    return render(request, "chat/conversation_detail.html", {
        "representative": representative,
        "all_messages": all_messages,
        "form": form,
    })


# def send_message(request, representative_id):
#     if request.method == 'POST':
#         content = request.POST.get('content')
#         sender = request.user
#         representative = Representative.objects.get(id=representative_id)
#         Message.objects.create(sender=sender, recipient=representative, content=content)
#         messages.success(request, "Your message has been delivered")
#         return redirect('app:index')
#     return render(request, "chat/conversation_detail.html", {
#         # "representative": representative,
#     })


# views.py

@login_required
def conversation_detail(request, representative_id):
    representative = Representative.objects.get(id=representative_id)
    conversation, created = Conversation.objects.get_or_create(user=request.user, representative=representative)
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            Message.objects.create(conversation=conversation, sender=request.user, content=content)
            messages.success(request, "Your message has been delivered")
            return redirect('chat:conversation_detail', representative_id=representative_id)
    else:
        form = MessageForm()
    return render(request, 'chat/conversation_detail.html', {
        'conversation': conversation,
        'representative': representative,
        'form': form,
    })


@login_required
def inbox(request):
    representatives = Representative.objects.all()
    rep_count = representatives.count()
    conversations = Conversation.objects.filter(user=request.user)
    convo_count = conversations.count()
    return render(request, 'chat/inbox.html', {
        'conversations': conversations,
        'representatives': representatives,
        'rep_count': rep_count,
        'convo_count': convo_count,
    })

templates/chat/conversation_detail.html
{%extends "partials/base.html"%}
{%load crispy_forms_tags%}

{%load static%}

{%block title%}Detail message{%endblock%}
{%block content%}
<style>
    .message-icon {
        display: none;
    }
</style>
<div class="container">
    <div class="d-flex text-center flex-column bg-body-tertiary rounded-4 shadow-sm">
        <h5 class="text-center mt-3">{{ representative.user.username }} <i
                class="bi text-primary bi-patch-check-fill"></i></h5>
        <p><i>Typically replies under 1 hour...</i></p>

    </div>
    <hr>
    <br><br>

    {%if conversation.messages%}
    <div class="container bg-body-tertiary rounded-3">
        {% for message in conversation.messages.all %}

        <div class="container rounded-5 p-3 d-flex flex-column">
            <div class="d-flex align-items-center">
                <img src="https://i.pinimg.com/564x/03/17/80/031780a9662ef257af01405e924b0d62.jpg" width="45"
                     height="45" class="rounded-5 mx-2 border border-dark" alt="">
                <h6 class="mt-2">{%if message.sender == request.user%}You{%else%}{{ message.sender.username }}<i
                        class="bi text-primary bi-patch-check-fill"></i>{%endif%} . <span><small
                        style="font-size: 12px;"
                        class="text-muted">{{message.timestamp|timesince}} ago <i class="bi bi-globe-europe-africa"></i></small></span>
                </h6>


            </div>
            <p class="mx-13 mt-2" style="font-size: 20px;">{{ message.content }}</p>

            <hr>
        </div>
        {% endfor %}
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="text-center">
                <button class="btn btn-primary w-50" type="submit"><i class="bi bi-send-fill"></i> Send Message</button>

            </div>
        </form>
    </div>
    {%else%}
    <div class="container mt-3 text-center">
        <h4>Start chatting</h4>
        <img width="200" src="{%static 'app_images/dog.gif'%}" alt="">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="text-center">
                <button class="btn btn-primary w-50" type="submit"><i class="bi bi-send-fill"></i> Send Message</button>

            </div>
        </form>

    </div>
    {%endif%}
</div>

{%endblock%}


templates/chat/inbox.html
{%extends "partials/base.html"%}
{%block title%}Inbox{%endblock%}
{%load static%}
{%block content%}
<style>
    .message-icon {
        display: none;
    }
    .scrollable-row {
    display: flex;
    overflow-x: auto;
    white-space: nowrap;
}

.item {
    flex: 0 0 auto;
    margin-right: 25px;
    text-align: center;
}

.item img {
    width: 60px;
    height: 60px;
    border-radius: 50%;
    object-fit: cover;
}

.item p {
    margin-top: 5px;
    font-size: 14px;
}

</style>

<!--AcTIVE MEMBERS-->

<h1 class="mt-3">Chats</h1>
<div class="alert alert-info justify-content-center d-flex align-items-center" role="alert">
    <i class="bi fs-4 bi-chat-square-text-fill mb-4 mx-3"></i>
    <div class="d-flex flex-column">
        <h4> Welcome to messaging.</h4>
        <h6>If you have any enquiries please Speak to any of our <strong>representatives right away</strong></h6>
        <small class="text-muted"><i>Typically replies under 1 hour</i></small>
    </div>


</div>
<br>
<h5>Our representatives <span class="badge bg-body-tertiary text-info">{{rep_count}}</span></h5>
<div class="scrollable-row bg-body-tertiary px-4 pt-2 rounded-4">
    {%for rep in representatives%}
    <div class="item">
        <a href="{%url 'chat:send_message' rep.id%}" class="text-decoration-none text-dark">
            <img width="45" height="45" class="border border-dark" src="{{rep.profile_pic.url}}" alt="User 1">
            <p>{{rep.user.username}} <i class="bi text-primary bi-patch-check-fill"></i></p>
        </a>
    </div>
    {%endfor%}
    <div class="item">
        <a href="#" class="text-decoration-none text-dark">
            <img width="45" height="45" class="border border-dark" src="{%static 'app_images/plus.gif'%}" alt="User 1">
            <p>More</p>
        </a>
    </div>

</div>
<hr>
<h5>Conversations <span class="badge bg-body-tertiary text-info">{{convo_count}}</span></h5>
<div class="d-flex w-100" style="">
    {%if conversations%}
    <div class="container-fluid d-flex flex-column mt-2">
        {% for conversation in conversations %}
        <a href="{% url 'chat:conversation_detail' conversation.representative.id %}" class="text-decoration-none my-2">
            <div class="bg-body-tertiary w-100 rounded-4 d-flex p-4 align-items-center">
                <img width="60" height="60" class="border border-dark rounded-circle mx-3" style="object-fit: cover;"
                     src="{{conversation.representative.profile_pic.url}}" alt="User 1">


                <a class="text-decoration-none text-dark mx-3"
                   href="{% url 'chat:conversation_detail' conversation.representative.id %}">{{conversation.representative.user.username}}
                    <i class="bi text-primary bi-patch-check-fill"></i></a>
            </div>
        </a>
        {% endfor %}

    </div>

    {%else%}
    <div class="container text-center">
        <img width="200" src="{%static 'app_images/ASSET9.png'%}" alt="">
        <h5>Start messaging</h5>
        <p>Select a <span class="span text-info">representative</span> to start chatting...</p>

    </div>
    {%endif%}


</div><br><br><br><br><br><br>


{%endblock%}